version: "3.4"
services:
  certapp-angular-v2-ui:
    image: us.icr.io/sbsd-prod/sbsd-certapp-angular-v2-ui:prd
    networks:
      - frontend
    build:
      args:
        configuration_file: prd
    environment:
      - SBSD_CERT_ENV=prd
      - USE_DOCKER_SECRETS=true
      - NEWRELIC_ENV=PRD
      - SERVICE_URL=dashboard-forum-svc.sbsd.virginia.gov
      - GOOGLE_ANALYTICS_TRACKING_ID
      - GOOGLE_MAP_API_KEY
      - GOOGLE_MAP_API_SERVER_KEY
    secrets:
      - prd_ui_auth0_client_id
      - prd_ui_auth0_client_secret
    deploy:
      resources:
        limits:
          memory: 128M
      replicas: 1
      restart_policy:
        condition: on-failure
    logging:
      driver: syslog
      options:
        syslog-address: "tcp+tls://logs6.papertrailapp.com:39872"
        tag: "{{.Name}}"

networks:
  frontend:
secrets:
  prd_ui_auth0_client_id:
    external: true
  prd_ui_auth0_client_secret:
    external: true

