export const SET_GLOBAL_LOADER = "SET_GLOBAL_LOADER"
export const SET_DISCUSSION_CATEGORY="SET_DISCUSSION_CATEGORY"
export const SET_CONTINUE="SET_CONTINUE"
export const SET_LOGGED_OUT_TIMEOUT = "SET_LOGGED_OUT_TIMEOUT"